// Generated by CoffeeScript 1.3.1
(function() {
  var Application, CLI, Config, Logger,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Logger = require('./logger');

  CLI = require('./cli');

  Config = require('./config');

  /**
   * The base application class.
  */


  Application = (function() {

    Application.name = 'Application';

    function Application(pkg_info) {
      this.pkg_info = pkg_info;
      this.abort = __bind(this.abort, this);

      this.config = Config.get();
      this.logger = Logger.get();
      this.cli = new CLI(this.pkg_info, this.logger);
    }

    Application.prototype.abort = function(str) {
      this.logger.info('aborting...');
      return process.exit(1);
    };

    return Application;

  })();

  module.exports = Application;

}).call(this);
