// Generated by CoffeeScript 1.3.3
(function() {
  var CLI, optimist;

  optimist = require('optimist');

  CLI = (function() {

    function CLI(pkg) {
      this.pkg = pkg;
      this.argv = optimist.usage("Usage: " + this.pkg.name).alias('c', 'config').describe('c', 'Load the configuration file').alias('h', 'help').describe('h', 'Shows this message').argv;
      if (process.argv.length <= 2) {
        optimist.showHelp();
        process.exit(1);
      }
    }

    return CLI;

  })();

  module.exports = CLI;

}).call(this);
